// Code generated by protoc-gen-go. DO NOT EDIT.
// source: anomlay_detector.proto

/*
Package detector is a generated protocol buffer package.

It is generated from these files:
	anomlay_detector.proto

It has these top-level messages:
	InputData
	AnomalyScore
*/
package detector

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type InputData struct {
	Key   string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *InputData) Reset()                    { *m = InputData{} }
func (m *InputData) String() string            { return proto.CompactTextString(m) }
func (*InputData) ProtoMessage()               {}
func (*InputData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *InputData) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *InputData) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type AnomalyScore struct {
	Score       float64 `protobuf:"fixed64,1,opt,name=score" json:"score,omitempty"`
	Explanation string  `protobuf:"bytes,2,opt,name=explanation" json:"explanation,omitempty"`
}

func (m *AnomalyScore) Reset()                    { *m = AnomalyScore{} }
func (m *AnomalyScore) String() string            { return proto.CompactTextString(m) }
func (*AnomalyScore) ProtoMessage()               {}
func (*AnomalyScore) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AnomalyScore) GetScore() float64 {
	if m != nil {
		return m.Score
	}
	return 0
}

func (m *AnomalyScore) GetExplanation() string {
	if m != nil {
		return m.Explanation
	}
	return ""
}

func init() {
	proto.RegisterType((*InputData)(nil), "detector.InputData")
	proto.RegisterType((*AnomalyScore)(nil), "detector.AnomalyScore")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AnomalyDetector service

type AnomalyDetectorClient interface {
	AnalyseData(ctx context.Context, in *InputData, opts ...grpc.CallOption) (*AnomalyScore, error)
}

type anomalyDetectorClient struct {
	cc *grpc.ClientConn
}

func NewAnomalyDetectorClient(cc *grpc.ClientConn) AnomalyDetectorClient {
	return &anomalyDetectorClient{cc}
}

func (c *anomalyDetectorClient) AnalyseData(ctx context.Context, in *InputData, opts ...grpc.CallOption) (*AnomalyScore, error) {
	out := new(AnomalyScore)
	err := grpc.Invoke(ctx, "/detector.AnomalyDetector/AnalyseData", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AnomalyDetector service

type AnomalyDetectorServer interface {
	AnalyseData(context.Context, *InputData) (*AnomalyScore, error)
}

func RegisterAnomalyDetectorServer(s *grpc.Server, srv AnomalyDetectorServer) {
	s.RegisterService(&_AnomalyDetector_serviceDesc, srv)
}

func _AnomalyDetector_AnalyseData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InputData)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AnomalyDetectorServer).AnalyseData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/detector.AnomalyDetector/AnalyseData",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AnomalyDetectorServer).AnalyseData(ctx, req.(*InputData))
	}
	return interceptor(ctx, in, info, handler)
}

var _AnomalyDetector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "detector.AnomalyDetector",
	HandlerType: (*AnomalyDetectorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyseData",
			Handler:    _AnomalyDetector_AnalyseData_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "anomlay_detector.proto",
}

func init() { proto.RegisterFile("anomlay_detector.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 189 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4b, 0xcc, 0xcb, 0xcf,
	0xcd, 0x49, 0xac, 0x8c, 0x4f, 0x49, 0x2d, 0x49, 0x4d, 0x2e, 0xc9, 0x2f, 0xd2, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x80, 0xf1, 0x95, 0x8c, 0xb9, 0x38, 0x3d, 0xf3, 0x0a, 0x4a, 0x4b, 0x5c,
	0x12, 0x4b, 0x12, 0x85, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18, 0x35, 0x38,
	0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26, 0x05, 0x46,
	0x0d, 0xc6, 0x20, 0x08, 0x47, 0xc9, 0x8d, 0x8b, 0xc7, 0x31, 0x2f, 0x3f, 0x37, 0x31, 0xa7, 0x32,
	0x38, 0x39, 0xbf, 0x28, 0x15, 0xa4, 0xaa, 0x18, 0xc4, 0x00, 0xeb, 0x64, 0x0c, 0x82, 0x70, 0x84,
	0x14, 0xb8, 0xb8, 0x53, 0x2b, 0x0a, 0x72, 0x12, 0xf3, 0x12, 0x4b, 0x32, 0xf3, 0xf3, 0xc0, 0x26,
	0x70, 0x06, 0x21, 0x0b, 0x19, 0xf9, 0x73, 0xf1, 0x43, 0xcd, 0x71, 0x81, 0xba, 0x47, 0xc8, 0x86,
	0x8b, 0xdb, 0x31, 0x2f, 0x31, 0xa7, 0xb2, 0x38, 0x15, 0xec, 0x22, 0x61, 0x3d, 0xb8, 0xcb, 0xe1,
	0xce, 0x94, 0x12, 0x43, 0x08, 0x22, 0x3b, 0x43, 0x89, 0x21, 0x89, 0x0d, 0xec, 0x3d, 0x63, 0x40,
	0x00, 0x00, 0x00, 0xff, 0xff, 0x8b, 0xc4, 0x7e, 0xa6, 0xf8, 0x00, 0x00, 0x00,
}
